import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {emptyState,computeTargets,localDate,type State} from '../../lib/domain';
const secret=readFileSync('.env.local','utf8').split('\n').find(l=>l.startsWith('APP_PASSPHRASE='))!.split('=').slice(1).join('=');
function fixture():State{const s=emptyState();const stats={height:165,weight:65,age:30,activity:1 as const,goal:'maintain' as const};const today=localDate(new Date(),'America/Los_Angeles');s.clock={zone:'America/Los_Angeles',anchorDay:today,anchorLocal:today};s.profile={...stats,targets:computeTargets(stats),overrides:{},baselineWeight:65,startDay:today};return s;}
test('gate rejects wrong passphrase and protects every write path',async({request,baseURL})=>{const wrong=await request.post('/api/auth',{headers:{origin:baseURL!},data:{passphrase:'deliberately-wrong'}});expect(wrong.status()).toBe(401);for(const path of ['/api/sync','/api/estimate'])expect((await request.post(path,{headers:{origin:baseURL!},data:[]})).status()).toBe(401);expect((await request.get('/api/state')).status()).toBe(401);expect((await request.post('/api/auth',{headers:{origin:'https://untrusted.example'},data:{passphrase:secret}})).status()).toBe(403);});
test('onboarding, all six one-tap habits, correction, calendar and no page scroll',async({page})=>{
 let server=emptyState();await page.route('**/api/state',r=>r.fulfill({json:server}));await page.route('**/api/sync',async r=>{const {apply}=await import('../../lib/domain');const ops=r.request().postDataJSON();for(const op of ops)server=apply(server,op);return r.fulfill({json:{state:server,accepted:ops.map((o:{id:string})=>o.id),rejected:[]}});});
 await page.goto('/');await page.getByLabel('Our little secret').fill(secret);await page.getByRole('button',{name:'Come on in'}).click();await expect(page.getByText('Hi, I’m Pip.')).toBeVisible();await page.getByLabel('Height · cm').fill('165');await page.getByLabel('Weight · kg',{exact:true}).fill('65');await page.getByLabel('Age',{exact:true}).fill('30');await page.getByRole('button',{name:'Make my little routine'}).click();await expect(page.getByRole('button',{name:'Workout complete',exact:true})).toBeVisible();
 for(const habit of ['Workout','Abs','Walk','Water','Protein','Calories']){const btn=page.getByRole('button',{name:habit+' complete',exact:true});await btn.click();await expect(btn).toHaveAttribute('aria-pressed','true');}
 await expect(page.getByText('All six, with a little love.')).toBeVisible();expect(await page.evaluate(()=>({page:document.documentElement.scrollHeight,height:innerHeight}))).toEqual({page:844,height:844});await page.screenshot({path:`evidence/home-complete-${test.info().project.name}.png`});
 await page.getByRole('button',{name:'Type it instead'}).click();await page.getByLabel('Calories · kcal').fill('600');await page.getByLabel('Protein · g',{exact:true}).fill('30');await page.getByRole('button',{name:'Confirm meal'}).click();await page.getByRole('button',{name:'Food today · 1'}).click();await page.getByRole('button',{name:'Correct'}).click();await page.getByLabel('Calories · kcal').fill('650');await page.getByRole('button',{name:'Confirm meal'}).click();await expect(page.getByText('650 kcal',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByText('600 kcal',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Your week',exact:true}).click();await expect(page.getByRole('button',{name:'Week',exact:true})).toHaveClass('active');await page.getByRole('button',{name:'Month',exact:true}).click();await page.screenshot({path:`evidence/month-${test.info().project.name}.png`});
});
test('offline optimistic writes, reconnect deduplication and manual model fallback',async({page,context})=>{
 let server=fixture();const seen=new Set<string>();await page.route('**/api/state',r=>r.fulfill({json:server}));await page.route('**/api/sync',async r=>{const {apply}=await import('../../lib/domain');const ops=r.request().postDataJSON();for(const op of ops){if(!seen.has(op.id)){server=apply(server,op);seen.add(op.id);}}await new Promise(resolve=>setTimeout(resolve,350));return r.fulfill({json:{state:server,accepted:ops.map((o:{id:string})=>o.id),rejected:[]}});});
 await page.addInitScript(s=>localStorage.setItem('flaccid75-v1',JSON.stringify({state:s,pending:[],unlocked:true})),server);await page.goto('/');await expect(page.getByRole('button',{name:'Workout complete',exact:true})).toBeVisible();await context.setOffline(true);
 await page.getByRole('button',{name:'Workout complete',exact:true}).click();await expect(page.getByRole('button',{name:'Workout complete',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Add a glass of water'}).click();await expect(page.getByText('0.25 / 2 L')).toBeVisible();
 // Confirm the pending queue before reconnecting.
 const local=await page.evaluate(()=>localStorage.getItem('flaccid75-v1'));expect(JSON.parse(local!).pending).toHaveLength(2);
 await page.screenshot({path:`evidence/offline-${test.info().project.name}.png`});await context.setOffline(false);await page.waitForFunction(()=>JSON.parse(localStorage.getItem('flaccid75-v1')!).pending.length===0);expect(seen.size).toBe(2);
 await page.route('**/api/estimate',r=>r.fulfill({status:503,json:{error:'Claude is unavailable.'}}));await page.getByRole('button',{name:'Type it instead'}).click();await page.getByLabel('What’s on your plate?').fill('two eggs');await page.getByRole('button',{name:'Estimate my meal'}).click();await expect(page.locator('.form-error')).toContainText('still log it by hand');await page.getByLabel('Calories · kcal').fill('160');await page.getByLabel('Protein · g',{exact:true}).fill('12');await page.getByRole('button',{name:'Confirm meal'}).click();await expect(page.getByText('160 kcal',{exact:true})).toBeVisible();
});
