import {test,expect,virtual} from './fixtures';
import {readFileSync} from 'node:fs';
import {emptyState,computeTargets,localDate,type State} from '../../lib/domain';
const secret=readFileSync('.env.local','utf8').split('\n').find(l=>l.startsWith('APP_PASSPHRASE='))!.split('=').slice(1).join('=');
function fixture():State{const s=emptyState();const stats={height:165,weight:65,age:30,activity:1 as const,goal:'maintain' as const};const today=localDate(new Date(),'America/Los_Angeles');s.clock={zone:'America/Los_Angeles',anchorDay:today,anchorLocal:today};s.profile={...stats,targets:computeTargets(stats),overrides:{},baselineWeight:65,startDay:today};return s;}
test('gate rejects wrong passphrase and protects every write path',async({request,baseURL})=>{test.skip(virtual,'needs a real server; scripts/deployment-check.mjs covers this against production');const wrong=await request.post('/api/auth',{headers:{origin:baseURL!},data:{passphrase:'deliberately-wrong'}});expect(wrong.status()).toBe(401);for(const path of ['/api/sync','/api/estimate'])expect((await request.post(path,{headers:{origin:baseURL!},data:[]})).status()).toBe(401);expect((await request.get('/api/state')).status()).toBe(401);expect((await request.post('/api/auth',{headers:{origin:'https://untrusted.example'},data:{passphrase:secret}})).status()).toBe(403);});
test('onboarding, all seven one-tap habits, celebration, correction, calendar and no page scroll',async({page})=>{
 let server=emptyState();await page.route('**/api/state',r=>r.fulfill({json:server}));await page.route('**/api/sync',async r=>{const {apply}=await import('../../lib/domain');const ops=r.request().postDataJSON();for(const op of ops)server=apply(server,op);return r.fulfill({json:{state:server,accepted:ops.map((o:{id:string})=>o.id),rejected:[]}});});
 if(virtual)await page.route('**/api/auth',r=>r.fulfill({json:{ok:true}}));
 await page.route('**/api/estimate',r=>r.fulfill({json:{items:[{name:'egg, whole, cooked, scrambled',grams:100,calories:149,protein:10,source:'usda',match:'Egg, whole, cooked, scrambled',fdcId:172187},{name:'bread, white, toasted',grams:50,calories:145,protein:4.5,source:'usda',match:'Bread, white, commercially prepared, toasted',fdcId:174925}],calories:294,protein:14.5,model:'test'}}));
 await page.goto('/');await page.getByLabel('Passphrase').fill(secret);await page.getByRole('button',{name:'Open'}).click();await expect(page.getByRole('heading',{name:'Welcome.'})).toBeVisible();await page.getByLabel('Height · cm').fill('165');await page.getByLabel('Weight · kg',{exact:true}).fill('65');await page.getByLabel('Age',{exact:true}).fill('30');await page.getByRole('button',{name:'Start'}).click();await expect(page.getByRole('button',{name:'Workout',exact:true})).toBeVisible();
 for(const habit of ['Workout','Abs','Walk','Floss']){const btn=page.getByRole('button',{name:habit,exact:true});await btn.click();await expect(btn).toHaveAttribute('aria-pressed','true');}
 // Water fills by pouring: eight glasses reach the 2 L target.
 const water=page.getByRole('button',{name:'Water',exact:true});for(let i=0;i<8;i++)await water.click();await expect(water).toHaveAttribute('aria-pressed','true');await expect(page.getByText('2 L')).toBeVisible();
 // Food: type a meal, see what was found, confirm once. Nothing is added before the confirmation.
 await page.getByRole('button',{name:'Log a meal'}).click();await page.getByLabel('What did you eat?').fill('two eggs and toast');await page.getByRole('button',{name:'Look it up'}).click();await expect(page.getByText('USDA · Egg, whole, cooked, scrambled')).toBeVisible();expect(Object.keys(server.days[Object.keys(server.days)[0]]?.meals??{})).toHaveLength(0);
 await page.getByRole('button',{name:'Not this'}).click();await expect(page.getByLabel('What did you eat?')).toBeVisible();expect(Object.keys(server.days[Object.keys(server.days)[0]]?.meals??{})).toHaveLength(0);
 await page.getByLabel('What did you eat?').fill('two eggs and toast');await page.getByRole('button',{name:'Look it up'}).click();await page.getByRole('button',{name:'Add to today'}).click();await expect(page.getByText('294 kcal')).toBeVisible();
 // Calories and protein need the targets; enter the rest by hand and correct one.
 await page.getByRole('button',{name:'Log a meal'}).click();await page.getByRole('button',{name:'Enter numbers'}).click();await page.getByLabel('Calories · kcal').fill('1600');await page.getByLabel('Protein · g',{exact:true}).fill('95');await page.getByRole('button',{name:'Add to today'}).click();
 // The celebration is the hero scene itself: no overlay, nothing to dismiss.
 await expect(page.getByRole('heading',{name:'Every one.'})).toBeVisible();await expect(page.locator('.hero')).toHaveClass(/is-complete/);await expect(page.locator('.hero .petal').first()).toBeAttached();await page.screenshot({path:`evidence/celebration-${test.info().project.name}.png`});
 expect(await page.evaluate(()=>({page:document.documentElement.scrollHeight,height:innerHeight}))).toEqual({page:844,height:844});await page.screenshot({path:`evidence/home-complete-${test.info().project.name}.png`});
 await page.getByRole('button',{name:'Log a meal'}).click();await page.getByRole('button',{name:'Today’s food · 2'}).click();await page.getByRole('button',{name:'Correct'}).first().click();await page.getByLabel('Calories · kcal').fill('300');await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText('1,900 kcal')).toBeVisible();await expect(page.getByRole('status')).toHaveCount(0);
 await page.getByRole('button',{name:'Progress',exact:true}).click();await expect(page.getByRole('button',{name:'Week',exact:true})).toHaveClass('active');await page.getByRole('button',{name:'Month',exact:true}).click();await page.screenshot({path:`evidence/month-${test.info().project.name}.png`});
});
test('offline optimistic writes, reconnect deduplication and manual fallback when the estimate fails',async({page,context})=>{
 let server=fixture();const seen=new Set<string>();await page.route('**/api/state',r=>r.fulfill({json:server}));await page.route('**/api/sync',async r=>{const {apply}=await import('../../lib/domain');const ops=r.request().postDataJSON();for(const op of ops){if(!seen.has(op.id)){server=apply(server,op);seen.add(op.id);}}await new Promise(resolve=>setTimeout(resolve,350));return r.fulfill({json:{state:server,accepted:ops.map((o:{id:string})=>o.id),rejected:[]}});});
 await page.addInitScript(s=>localStorage.setItem('flaccid75-v1',JSON.stringify({state:s,pending:[],unlocked:true})),server);await page.goto('/');await expect(page.getByRole('button',{name:'Workout',exact:true})).toBeVisible();await context.setOffline(true);
 await page.getByRole('button',{name:'Workout',exact:true}).click();await expect(page.getByRole('button',{name:'Workout',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Water',exact:true}).click();await expect(page.getByText('0.25 L')).toBeVisible();
 const local=await page.evaluate(()=>localStorage.getItem('flaccid75-v1'));expect(JSON.parse(local!).pending).toHaveLength(2);
 // Nothing on screen tells her about the queue. It syncs when it can.
 await expect(page.getByText(/waiting to sync/)).toHaveCount(0);
 await page.screenshot({path:`evidence/offline-${test.info().project.name}.png`});await context.setOffline(false);await page.waitForFunction(()=>JSON.parse(localStorage.getItem('flaccid75-v1')!).pending.length===0);expect(seen.size).toBe(2);
 await page.route('**/api/estimate',r=>r.fulfill({status:503,json:{error:'That could not be looked up right now.'}}));await page.getByRole('button',{name:'Log a meal'}).click();await page.getByLabel('What did you eat?').fill('two eggs');await page.getByRole('button',{name:'Look it up'}).click();await expect(page.locator('.form-error')).toContainText('could not be looked up');await page.getByRole('button',{name:'Enter numbers'}).click();await page.getByLabel('Calories · kcal').fill('160');await page.getByLabel('Protein · g',{exact:true}).fill('12');await page.getByRole('button',{name:'Add to today'}).click();await expect(page.getByText('160 kcal')).toBeVisible();
});
