import {test,expect} from '@playwright/test';
import {emptyState,computeTargets,localDate,addDays,apply,type State} from '../../lib/domain';
test('rest confirmation, exact quota, backfill, rescue, trend and settings',async({page})=>{
 const today=localDate(new Date(),'America/Los_Angeles'),past=addDays(today,-1);const stats={height:165,weight:65,age:30,activity:1 as const,goal:'maintain' as const};let state:State={...emptyState(),clock:{zone:'America/Los_Angeles',anchorDay:today,anchorLocal:today},profile:{...stats,targets:computeTargets(stats),overrides:{},baselineWeight:65,startDay:past}};
 await page.route('**/api/state',r=>r.fulfill({json:state}));await page.route('**/api/sync',r=>{const ops=r.request().postDataJSON();for(const op of ops)state=apply(state,op);return r.fulfill({json:{state,accepted:ops.map((o:{id:string})=>o.id),rejected:[]}});});await page.addInitScript(s=>localStorage.setItem('flaccid75-v1',JSON.stringify({state:s,pending:[],unlocked:true})),state);await page.goto('/');
 await page.getByRole('button',{name:'Rest today'}).click();await expect(page.getByRole('button',{name:'Rest today'}).nth(1)).toBeVisible();expect(state.days[today]?.rest??false).toBe(false);await page.getByRole('button',{name:'Rest today'}).nth(1).click();await expect(page.getByText('0 rest day left')).toBeVisible();await expect(page.getByRole('button',{name:'Undo rest'})).toBeVisible();
 await page.getByRole('button',{name:'Week',exact:true}).click();await page.getByLabel('Open any past day').fill(past);await expect(page.getByText('Not checked: Workout, Abs, Walk, Water, Protein, Calories, Floss.')).toBeVisible();await page.getByRole('button',{name:'Rescue day',exact:true}).click();expect(state.days[past]?.rescued??false).toBe(false);await page.getByRole('button',{name:'Rescue this day'}).click();await expect(page.getByRole('button',{name:past+' rescued backfilled',exact:true})).toBeVisible();await page.getByRole('button',{name:'Backfill this day'}).click();await page.getByRole('button',{name:'Workout',exact:true}).click();await expect(page.getByRole('button',{name:'Workout',exact:true})).toHaveAttribute('aria-pressed','true');expect(state.days[past].backfilled).toBe(true);
 await page.getByRole('button',{name:'You',exact:true}).click();await page.getByRole('button',{name:'Daily targets'}).click();await page.getByLabel('Protein · g',{exact:true}).fill('125');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Today',exact:true}).click();await expect(page.getByText('0 / 125 g')).toBeVisible();await page.getByRole('button',{name:'Trends',exact:true}).click();await expect(page.getByText('Two weigh-ins start a trend')).toBeVisible();await page.screenshot({path:`evidence/trends-${test.info().project.name}.png`});
});
