import {test,expect} from './fixtures';
import {open,seed,todayIn,op} from './helpers';
import {apply,entriesInOrder} from '../../lib/domain';
const items=['Rice','Soup','Beans'].map(name=>({name,grams:100,calories:200,protein:10,source:'estimate' as const}));
function meal(){const day=todayIn(),id=crypto.randomUUID();return {day,id,state:apply(seed(),op(day,{type:'meal',mealId:id,description:'Three bowls',calories:600,protein:30,items}))};}
for(const mode of ['saved','manual'])for(const char of ['x','🍚'])test(`R5 ${mode} ${char} description refuses middle overflow and preserves replacement undo`,async({page})=>{
 const {day,id,state}=meal();const box=await open(page,mode==='saved'?state:seed(),{hash:'food'});
 if(mode==='saved')await page.getByRole('button',{name:'Correct meal 1'}).click();
 else {await page.getByRole('button',{name:'Log a meal',exact:true}).click();await page.getByRole('button',{name:'Enter numbers'}).click();await page.getByLabel('Calories · kcal').fill('600');await page.getByLabel('Protein · g').fill('30');}
 const field=page.getByLabel('Description',{exact:true}),value='A'+char.repeat(998)+'Z';await field.fill(value);await field.evaluate((el:HTMLTextAreaElement)=>el.setSelectionRange(1,1));await field.pressSequentially('Q');expect(await field.inputValue()).toBe(value);expect(await field.evaluate((el:HTMLTextAreaElement)=>el.selectionStart)).toBe(1);
 const pasteBlocked=await field.evaluate(el=>{const data=new DataTransfer();data.setData('text/plain','PASTE');return !el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});expect(pasteBlocked).toBe(true);await expect(field).toHaveValue(value);
 await page.getByRole('button',{name:mode==='saved'?'Save':'Add to today',exact:true}).click();await expect.poll(()=>mode==='saved'?box.state.days[day].meals[id]?.description:Object.values(box.state.days[day]?.meals??{})[0]?.description).toBe(value);await page.reload();await page.getByRole('button',{name:'Correct meal 1'}).click();await expect(field).toHaveValue(value);
 await field.evaluate((el:HTMLTextAreaElement)=>el.setSelectionRange(1,1));await field.press('ArrowRight');await field.press('Shift+ArrowLeft');await field.pressSequentially('Q');await expect(field).toHaveValue('AQ'+char.repeat(997)+'Z');await field.press('ControlOrMeta+z');await expect(field).toHaveValue(value);
 await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(()=>mode==='saved'?box.state.days[day].meals[id]?.description:Object.values(box.state.days[day]?.meals??{})[0]?.description).toBe(value);await page.reload();await page.getByRole('button',{name:'Correct meal 1'}).click();await expect(field).toHaveValue(value);
});
for(const input of ['keyboard','double click','double tap'])test(`R5 item removal by ${input} keeps identity and moves focus safely`,async({page})=>{
 const {day,id,state}=meal();const box=await open(page,state,{hash:'food'});await page.getByRole('button',{name:'Correct meal 1'}).click();await page.getByRole('group',{name:'Item 2: Soup',exact:true}).evaluate(el=>el.setAttribute('data-original-soup','true'));
 const remove=page.getByRole('button',{name:'Remove item 1: Rice',exact:true});if(input==='keyboard'){await remove.focus();await page.keyboard.press('Enter');await expect(page.getByRole('group',{name:'Item 1: Soup',exact:true}).getByLabel('Item name')).toBeFocused();await page.keyboard.press('Enter');}else if(input==='double click')await remove.dblclick();else {await remove.scrollIntoViewIfNeeded();const rect=await remove.boundingBox();expect(rect).not.toBeNull();const x=rect!.x+rect!.width/2,y=rect!.y+rect!.height/2;await page.touchscreen.tap(x,y);await page.touchscreen.tap(x,y);}
 await expect(page.locator('.items fieldset')).toHaveCount(2);await expect(page.getByRole('group',{name:'Item 1: Soup',exact:true})).toHaveAttribute('data-original-soup','true');
 await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(()=>box.state.days[day].meals[id].items?.map(i=>i.name)).toEqual(['Soup','Beans']);await page.reload();await page.getByRole('button',{name:'Correct meal 1'}).click();
 await page.getByRole('button',{name:'Remove item 2: Beans',exact:true}).click();await expect(page.getByLabel('Item name')).toBeFocused();await page.getByLabel('Item name').fill('');await expect(page.getByRole('button',{name:'Remove item 1: Unnamed item',exact:true})).toBeVisible();await page.getByRole('button',{name:'Remove item 1: Unnamed item',exact:true}).click();await expect(page.locator('.sum')).toBeFocused();await expect(page.locator('.sum')).toContainText('0 kcal · 0 g protein');
});
test('R5 zero portion warning clears on that item correction and Not this',async({page})=>{
 await open(page,seed(),{hash:'food'});await page.route('**/api/estimate',r=>r.fulfill({json:{items:[{...items[0],grams:0},items[1]]}}));await page.getByRole('button',{name:'Log a meal',exact:true}).click();await page.getByLabel('What did you eat?').fill('Rice and soup');await page.getByRole('button',{name:'Look it up'}).click();
 const rice=page.getByRole('group',{name:'Item 1: Rice',exact:true});await rice.getByLabel('Portion · g').fill('100');await expect(page.getByRole('alert')).toContainText('starting portion was 0 g');await page.getByRole('group',{name:'Item 2: Soup',exact:true}).getByLabel('Calories · kcal').fill('250');await expect(page.getByRole('alert')).toBeVisible();await rice.getByLabel('Calories · kcal').fill('250');await rice.getByLabel('Protein · g').fill('10');await expect(page.getByRole('alert')).toHaveCount(0);
 await rice.getByLabel('Portion · g').fill('0');await rice.getByLabel('Item name').focus();await rice.getByLabel('Portion · g').fill('100');await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Not this'}).click();await expect(page.getByRole('alert')).toHaveCount(0);
});
test('R5 walk removal retains order, completion and keyboard focus through reload',async({page})=>{
 const day=todayIn(),ids=['cccccccc-cccc-4ccc-8ccc-cccccccccccc','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'];let state=seed();for(let i=0;i<3;i++)state=apply(state,op(day,{type:'session',habit:'walk',walkId:ids[i],seconds:(i+1)*600,done:true}));const box=await open(page,state,{hash:'walk'});
 await page.getByRole('button',{name:'Remove walk 2',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Remove walk 2',exact:true})).toBeFocused();await expect.poll(()=>entriesInOrder(box.state.days[day].walkLog!,box.state.days[day].walkOrder).map(([id])=>id)).toEqual([ids[0],ids[2]]);await page.reload();await expect(page.getByRole('group',{name:'Walk entries'}).locator('.meal-row p')).toHaveText(['10:00','30:00']);await page.getByRole('button',{name:'Remove walk 2',exact:true}).click();await expect(page.getByRole('button',{name:'Remove walk 1',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByLabel('Walk minutes')).toBeFocused();await expect(page.getByRole('checkbox',{name:'Walk complete',checked:true})).toBeVisible();await page.reload();await expect(page.getByRole('group',{name:'Walk entries'})).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'Walk complete',checked:true})).toBeVisible();
});
for(const habit of ['walk','workout','abs','floss'])test(`R5 ${habit} completion text activates one named checkbox in both directions`,async({page})=>{
 const day=todayIn();const box=await open(page,seed(),{hash:habit});const name=habit[0].toUpperCase()+habit.slice(1)+' complete',row=page.locator('.completion-row'),toggle=page.getByRole('checkbox',{name,exact:true});await expect(toggle).toHaveAttribute('aria-labelledby',/\S+/);await row.getByText(name,{exact:true}).click();await expect(toggle).toBeChecked();await expect.poll(()=>box.state.days[day]?.checks[habit as 'walk']).toBe(true);await page.reload();await expect(toggle).toBeChecked();await row.getByText(name,{exact:true}).click();await expect(toggle).not.toBeChecked();await toggle.focus();await page.keyboard.press('Space');await expect(toggle).toBeChecked();await page.keyboard.press('Enter');await expect(toggle).not.toBeChecked();await expect.poll(()=>box.state.days[day]?.checks[habit as 'walk']).toBe(false);await page.reload();await expect(toggle).not.toBeChecked();await page.setViewportSize({width:320,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('R5 completed floss has no empty stage subtitle',async({page})=>{const day=todayIn();await open(page,apply(seed(),op(day,{type:'check',habit:'floss',value:true})),{hash:'floss'});await expect(page.locator('.stage-copy>span')).toHaveCount(0);});
